pipeline.id: main
pipeline.batch.size: 250
pipeline.batch.delay: 50
pipeline.workers: 4
pipeline.unsafe.shutdown: false
path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs
http.host: 0.0.0.0
http.port: 9600
log.level: info
log.format: json
queue.type: persisted
queue.path: /usr/share/logstash/data/queue
queue.page_capacity: 64mb
queue.max_bytes: 1gb
queue.checkpoint.writes: 1024