export enum ErrorCode {
  // Network & API
  NETWORK_ERROR = 'NETWORK_ERROR',
  API_TIMEOUT = 'API_TIMEOUT',
  API_RESPONSE_ERROR = 'API_RESPONSE_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // WebSocket
  WEBSOCKET_DISCONNECTED = 'WEBSOCKET_DISCONNECTED',
  WEBSOCKET_CONNECTION_FAILED = 'WEBSOCKET_CONNECTION_FAILED',
  WEBSOCKET_MESSAGE_PARSE_ERROR = 'WEBSOCKET_MESSAGE_PARSE_ERROR',

  // Store & Data
  STORE_CORRUPTION = 'STORE_CORRUPTION',
  DATA_NORMALIZATION_FAILED = 'DATA_NORMALIZATION_FAILED',
  STATE_TRANSITION_ERROR = 'STATE_TRANSITION_ERROR',

  // Rendering & UI
  RENDER_FAILURE = 'RENDER_FAILURE',
  WIDGET_CRASH = 'WIDGET_FAILURE',
  ROUTE_ERROR = 'ROUTE_ERROR',
  CHUNCK_LOAD_FAILURE = 'CHUNK_LOAD_FAILURE',

  // Trading & Business Logic
  ORDER_VALIDATION_FAILED = 'ORDER_VALIDATION_FAILED',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  RISK_LIMIT_EXCEEDED = 'RISK_LIMIT_EXCEEDED',
  STRATEGY_EXECUTION_ERROR = 'STRATEGY_EXECUTION_ERROR',

  // Unknown
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

export type ErrorSeverity = 'low' | 'medium' | 'high' | 'critical';
