// Re-export all from trading.types as primary types
export * from './trading.types'

// Re-export only unique types from api.types to avoid collisions
export type {
  ApiResponse,
  PaginatedResponse,
  Pagination,
  ErrorResponse,
  ValidationError,
  User,
  UserProfile,
  UserPreferences,
  UserLimits,
  LoginRequest,
  LoginResponse,
  RefreshTokenRequest,
  RefreshTokenResponse,
  RegisterRequest,
  ChangePasswordRequest,
  Quote, // api.types.ts has Quote, trading.types.ts has MarketQuote
  MarketDepth as APIMarketDepth,
  OrderBookEntry,
  Candle,
  CandleData,
  Index,
  MarketOverview,
  TopMover,
  Order as APIOrder,
  CreateOrderRequest as APICreateOrderRequest,
  ModifyOrderRequest,
  OrderStats,
  Position as APIPosition,
  PositionSummary,
  Trade as APITrade,
  DailyTradeSummary,
  Funds,
  Transaction,
  Holding as APIHolding,
  HoldingsSummary as APIHoldingsSummary,
  Strategy,
  StrategyParameters,
  RiskSettings,
  StrategyStatistics,
  CreateStrategyRequest,
  StrategySignal,
  Signal,
  LiveSignalsSummary,
  SignalGenerationRequest,
  SignalJob,
  Notification,
  DashboardSummary,
  PerformanceData,
  DailyPerformance,
  SymbolPerformance,
  Watchlist,
  CreateWatchlistRequest,
  UpdateWatchlistRequest,
  AddStocksRequest,
  Settings,
  UpdateSettingsRequest,
  StrategyConfig,
  StrategyType,
  StrategyStatus,
  ExecutionSettings,
  IndicatorConfig,
  Condition,
  StrategyStatisticsV2,
  CreateStrategyRequestV2,
  UpdateStrategyRequest,
  StrategySignalV2,
  EngineStatus,
  EngineMetrics,
  StrategyInstanceStatus,
  BacktestResult,
  BacktestTrade,
  BacktestRequest,
  PaperPortfolio,
  PaperTrade,
  PaperPerformance,
  RiskSummary
} from './api.types'

// WebSocket types
export type { WSEvent, WSConnectionStatus, WSState, WSEventHandlers } from './websocket.types'
export type {
  MarketTickData,
  MarketDepthData,
  OrderBookEntry as WSOrderBookEntry,
  MarketIndicesData,
  OrderUpdateData,
  PositionUpdateData,
  PnLUpdateData,
  TradeExecutedData,
  NotificationData,
  StrategyUpdateData,
  AISignalData,
  MarketStatusData,
  SubscribeMarketEvent,
  UnsubscribeMarketEvent,
  SubscribeWatchlistEvent,
  SubscribeUserEvent,
  PlaceOrderEvent,
} from './websocket.types'
