server.name: trading-kibana
server.host: "0.0.0.0"
server.port: 5601
elasticsearch.hosts: http://elasticsearch:9200
elasticsearch.username: elastic
elasticsearch.password: ${ELASTIC_PASSWORD}
elasticsearch.requestTimeout: 60000
logging.verbose: true
logging.dest: stdout
ops.cGroupOverrides.cpuPath: /sys/fs/cgroup/cpu,cpuacct
ops.cGroupOverrides.cpuAcctPath: /sys/fs/cgroup/cpu,cpuacct
ops.interval: 10000
server.maxPayloadBytes: 16777216
server.defaultRoute: /app/kibana
csp.strict: true
csp.warnLegacyBrowsers: false
telemetry.enabled: false
telemetry.optIn: false
newsfeed.enabled: false
console.enabled: true
map.tilemap.options.reuseTiles: true
visualization:tabular:height: auto
savedObjects:maxImportPayloadBytes: 33554432
savedObjects:maxImportExportSize: 20000
tracing:service:enabled: true
tracing:service:url: http://apm-server:8200
securityAnalytics:enabled: false