"""
Strategy Manager
================
Central management for all active and historical strategies.
"""

import logging
from datetime import datetime
from typing import Dict, List, Optional, Any
from bson import ObjectId

from app.database.connection import get_db

logger = logging.getLogger('strategy_manager')

class StrategyManager:
    """
    Manages strategy lifecycle: loading, storage, and performance tracking.
    """

    def __init__(self):
        self.logger = logging.getLogger('strategy_manager')

    def get_all_strategies(self, user_id: str, mode: str = 'paper') -> List[Dict]:
        """Get all strategies for a user."""
        db = get_db()
        if db is None:
            return []

        try:
            strategies = list(db.strategies.find({'user_id': user_id, 'mode': mode}))
            for s in strategies:
                s['_id'] = str(s['_id'])
            return strategies
        except Exception as e:
            logger.error(f"Error fetching strategies: {e}")
            return []

    def get_strategy(self, strategy_id: str) -> Optional[Dict]:
        """Get strategy by ID."""
        db = get_db()
        if db is None:
            return None

        try:
            strategy = db.strategies.find_one({'_id': ObjectId(strategy_id)})
            if strategy:
                strategy['_id'] = str(strategy['_id'])
            return strategy
        except Exception as e:
            logger.error(f"Error fetching strategy {strategy_id}: {e}")
            return None

    def create_strategy(self, data: Dict) -> Optional[str]:
        """Create a new strategy."""
        db = get_db()
        if db is None:
            return None

        try:
            data['created_at'] = datetime.utcnow()
            data['updated_at'] = datetime.utcnow()
            result = db.strategies.insert_one(data)
            return str(result.inserted_id)
        except Exception as e:
            logger.error(f"Error creating strategy: {e}")
            return None

    def update_strategy(self, strategy_id: str, data: Dict) -> bool:
        """Update an existing strategy."""
        db = get_db()
        if db is None:
            return False

        try:
            data['updated_at'] = datetime.utcnow()
            result = db.strategies.update_one(
                {'_id': ObjectId(strategy_id)},
                {'$set': data}
            )
            return result.modified_count > 0
        except Exception as e:
            logger.error(f"Error updating strategy {strategy_id}: {e}")
            return False

    def delete_strategy(self, strategy_id: str) -> bool:
        """Delete a strategy."""
        db = get_db()
        if db is None:
            return False

        try:
            result = db.strategies.delete_one({'_id': ObjectId(strategy_id)})
            return result.deleted_count > 0
        except Exception as e:
            logger.error(f"Error deleting strategy {strategy_id}: {e}")
            return False

    def toggle_strategy(self, strategy_id: str, is_active: bool) -> bool:
        """Enable or disable a strategy."""
        db = get_db()
        if db is None:
            return False

        try:
            result = db.strategies.update_one(
                {'_id': ObjectId(strategy_id)},
                {'$set': {'is_active': is_active, 'updated_at': datetime.utcnow()}}
            )
            return result.modified_count > 0
        except Exception as e:
            logger.error(f"Error toggling strategy {strategy_id}: {e}")
            return False

    def log_signal(self, strategy_id: str, signal: Dict) -> bool:
        """Log a trading signal generated by a strategy."""
        db = get_db()
        if db is None:
            return False

        try:
            signal['strategy_id'] = ObjectId(strategy_id)
            signal['created_at'] = datetime.utcnow()
            db.signals.insert_one(signal)
            return True
        except Exception as e:
            logger.error(f"Error logging signal: {e}")
            return False

    def get_strategy_performance(
        self, 
        strategy_id: str,
        period: str = 'all'
    ) -> Optional[Dict]:
        """Get strategy performance metrics."""
        db = get_db()
        if db is None:
            return None

        try:
            query = {'strategy_id': strategy_id}
            if period != 'all':
                from datetime import timedelta
                start_date = datetime.utcnow() - timedelta(days=int(period))
                query['executed_at'] = {'$gte': start_date}

            trades = list(db.paper_trades.find(query))

            if not trades:
                return None

            total_trades = len(trades)
            winning = sum(1 for t in trades if t.get('pnl', 0) > 0)
            losing = total_trades - winning

            total_pnl = sum(t.get('pnl', 0) for t in trades)
            avg_pnl = total_pnl / total_trades if total_trades > 0 else 0

            wins = [t.get('pnl', 0) for t in trades if t.get('pnl', 0) > 0]
            losses = [abs(t.get('pnl', 0)) for t in trades if t.get('pnl', 0) < 0]

            avg_win = sum(wins) / len(wins) if wins else 0
            avg_loss = sum(losses) / len(losses) if losses else 0

            return {
                'total_trades': total_trades,
                'winning_trades': winning,
                'losing_trades': losing,
                'win_rate': (winning / total_trades * 100) if total_trades > 0 else 0,
                'total_pnl': total_pnl,
                'avg_pnl': avg_pnl,
                'avg_win': avg_win,
                'avg_loss': avg_loss,
                'profit_factor': (avg_win / avg_loss) if avg_loss > 0 else 0
            }

        except Exception as e:
            logger.error(f"Error getting performance: {e}")
            return None
