---
apiVersion: v1
kind: Namespace
metadata:
  name: trading-platform
  labels:
    name: trading-platform
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-stack
  labels:
    name: elastic-stack
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: backup
  labels:
    name: backup
    environment: production